"""Builds Libretto's string catalog. Keys Tables already translates reuse its
translations, so the two apps speak the same words for the same things."""
import json, sys, os

LANGS = ["en", "ja", "ko", "zh-Hans", "zh-Hant"]
here = os.path.dirname(os.path.abspath(__file__))
tables_path = os.path.join(here, "..", "..", "Tables", "Tables", "Support", "Localizable.xcstrings")
out_path = os.path.join(here, "..", "Libretto", "Support", "Localizable.xcstrings")

S = {
 "ActionBar.Alignment": ["Alignment", "配置", "정렬", "对齐", "對齊"],
 "ActionBar.Bullets": ["Bulleted List", "箇条書き", "글머리 기호 목록", "项目符号列表", "項目符號清單"],
 "ActionBar.DeleteTable": ["Delete Table", "表を削除", "표 삭제", "删除表格", "刪除表格"],
 "ActionBar.EditTable": ["Edit Table", "表を編集", "표 편집", "编辑表格", "編輯表格"],
 "ActionBar.Format": ["Format", "書式", "서식", "格式", "格式"],
 "ActionBar.Insert": ["Insert", "挿入", "삽입", "插入", "插入"],
 "ActionBar.Numbering": ["Numbered List", "段落番号", "번호 매기기 목록", "编号列表", "編號清單"],
 "ActionBar.PageSetup": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "ActionBar.Paragraph": ["Paragraph", "段落", "단락", "段落", "段落"],
 "ActionBar.Style": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Alert.Picture.Failed": ["The picture couldn’t be loaded.", "画像を読み込めませんでした。", "사진을 불러올 수 없습니다.", "无法载入图片。", "無法載入圖片。"],
 "Alignment.Center": ["Center", "中央揃え", "가운데 정렬", "居中", "置中"],
 "Alignment.Justified": ["Justified", "両端揃え", "양쪽 정렬", "两端对齐", "左右對齊"],
 "Alignment.Left": ["Left", "左揃え", "왼쪽 정렬", "左对齐", "靠左對齊"],
 "Alignment.Right": ["Right", "右揃え", "오른쪽 정렬", "右对齐", "靠右對齊"],
 "Block.Preserved.Placeholder": ["Content Libretto can’t show", "Librettoで表示できないコンテンツ", "Libretto에서 표시할 수 없는 콘텐츠", "Libretto 无法显示的内容", "Libretto 無法顯示的內容"],
 "Document.DefaultName": ["Document", "書類", "문서", "文稿", "文件"],
 "Error.MissingBody": ["This document has no body to show.", "この書類には表示できる本文がありません。", "이 문서에는 표시할 본문이 없습니다.", "此文稿没有可显示的正文。", "此文件沒有可顯示的內文。"],
 "Error.MissingMainDocument": ["This file isn’t a Word document.", "このファイルはWord書類ではありません。", "이 파일은 Word 문서가 아닙니다.", "此文件不是 Word 文稿。", "此檔案不是 Word 文件。"],
 "Format.Section.Highlight": ["Highlight", "蛍光ペン", "형광펜", "突出显示", "螢光筆"],
 "Format.Subscript": ["Subscript", "下付き", "아래 첨자", "下标", "下標"],
 "Format.Superscript": ["Superscript", "上付き", "위 첨자", "上标", "上標"],
 "Highlight.None": ["No highlight", "蛍光ペンなし", "형광펜 없음", "无突出显示", "無螢光筆"],
 "Highlight.yellow": ["Yellow highlight", "黄色の蛍光ペン", "노란색 형광펜", "黄色突出显示", "黃色螢光筆"],
 "Highlight.green": ["Green highlight", "緑の蛍光ペン", "초록색 형광펜", "绿色突出显示", "綠色螢光筆"],
 "Highlight.cyan": ["Turquoise highlight", "水色の蛍光ペン", "청록색 형광펜", "青绿色突出显示", "青綠色螢光筆"],
 "Highlight.magenta": ["Pink highlight", "ピンクの蛍光ペン", "분홍색 형광펜", "粉红色突出显示", "粉紅色螢光筆"],
 "Highlight.red": ["Red highlight", "赤の蛍光ペン", "빨간색 형광펜", "红色突出显示", "紅色螢光筆"],
 "Highlight.blue": ["Blue highlight", "青の蛍光ペン", "파란색 형광펜", "蓝色突出显示", "藍色螢光筆"],
 "Highlight.lightGray": ["Grey highlight", "灰色の蛍光ペン", "회색 형광펜", "灰色突出显示", "灰色螢光筆"],
 "Highlight.darkYellow": ["Dark yellow highlight", "濃い黄色の蛍光ペン", "진한 노란색 형광펜", "深黄色突出显示", "深黃色螢光筆"],
 "Launch.NewDocument": ["Create Document", "書類を作成", "문서 만들기", "创建文稿", "建立文件"],
 "Insert.PageBreak": ["Page Break", "改ページ", "페이지 나누기", "分页符", "分頁符號"],
 "Insert.Picture": ["Picture…", "画像…", "사진…", "图片…", "圖片…"],
 "Insert.Table": ["Table…", "表…", "표…", "表格…", "表格…"],
 "InsertTable.Columns": ["Columns: %lld", "列：%lld", "열: %lld", "列：%lld", "欄：%lld"],
 "InsertTable.Insert": ["Insert Table", "表を挿入", "표 삽입", "插入表格", "插入表格"],
 "InsertTable.Rows": ["Rows: %lld", "行：%lld", "행: %lld", "行：%lld", "列：%lld"],
 "Mobile.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Mobile.Picture": ["Picture", "画像", "사진", "图片", "圖片"],
 "Mobile.WordCount": ["%lld words", "%lld語", "%lld단어", "%lld 个词", "%lld 個字詞"],
 "Notice.UnsupportedFeatures.Message": ["This document uses things Libretto can show but not edit. They’re kept as they are, and saved back with the document. Libretto never runs macros.", "この書類には、Librettoで表示はできても編集できない要素が含まれています。これらはそのまま保持され、書類と一緒に保存されます。Librettoがマクロを実行することはありません。", "이 문서에는 Libretto에서 표시할 수는 있지만 편집할 수 없는 요소가 있습니다. 이러한 요소는 그대로 유지되며 문서와 함께 저장됩니다. Libretto는 매크로를 실행하지 않습니다.", "此文稿包含 Libretto 可以显示但无法编辑的内容。这些内容会原样保留，并随文稿一起存储。Libretto 绝不会运行宏。", "此文件包含 Libretto 可以顯示但無法編輯的內容。這些內容會原樣保留，並隨文件一起儲存。Libretto 絕不會執行巨集。"],
 "Notice.UnsupportedFeatures.Title": ["Some Parts Are Read-Only", "一部は読み取り専用です", "일부는 읽기 전용입니다", "部分内容为只读", "部分內容為唯讀"],
 "PageSetup.Landscape": ["Landscape", "横", "가로", "横向", "橫向"],
 "PageSetup.Margins.Description": ["Top and bottom %1$@, sides %2$@", "上下 %1$@、左右 %2$@", "위아래 %1$@, 양옆 %2$@", "上下 %1$@，左右 %2$@", "上下 %1$@，左右 %2$@"],
 "PageSetup.Margins.Moderate": ["Moderate", "やや狭い", "보통", "适中", "適中"],
 "PageSetup.Margins.Narrow": ["Narrow", "狭い", "좁게", "窄", "窄"],
 "PageSetup.Margins.Normal": ["Normal", "標準", "기본", "常规", "標準"],
 "PageSetup.Margins.Wide": ["Wide", "広い", "넓게", "宽", "寬"],
 "PageSetup.Orientation": ["Orientation", "向き", "방향", "方向", "方向"],
 "PageSetup.Paper": ["Paper Size", "用紙サイズ", "용지 크기", "纸张大小", "紙張大小"],
 "PageSetup.Paper.Custom": ["Custom (%.0f × %.0f mm)", "カスタム（%.0f × %.0f mm）", "사용자 지정(%.0f × %.0f mm)", "自定（%.0f × %.0f 毫米）", "自訂（%.0f × %.0f 公釐）"],
 "PageSetup.Paper.Legal": ["US Legal", "US リーガル", "US 리걸", "美国法律用纸", "美國法律用紙"],
 "PageSetup.Paper.Letter": ["US Letter", "US レター", "US 레터", "美国信纸", "美國信紙"],
 "PageSetup.Portrait": ["Portrait", "縦", "세로", "纵向", "直向"],
 "PageSetup.Section.Margins": ["Margins", "余白", "여백", "页边距", "邊界"],
 "PageSetup.Section.Paper": ["Paper", "用紙", "용지", "纸张", "紙張"],
 "Panel.Format.Title": ["Format", "書式", "서식", "格式", "格式"],
 "Panel.InsertTable.Title": ["Insert Table", "表を挿入", "표 삽입", "插入表格", "插入表格"],
 "Panel.PageSetup.Title": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "Panel.Paragraph.Title": ["Paragraph", "段落", "단락", "段落", "段落"],
 "Panel.Table.Title": ["Table", "表", "표", "表格", "表格"],
 "Paragraph.Alignment": ["Alignment", "配置", "정렬", "对齐", "對齊"],
 "Paragraph.Bullets": ["Bullets", "箇条書き", "글머리 기호", "项目符号", "項目符號"],
 "Paragraph.Indent": ["Indent", "インデント", "들여쓰기", "缩进", "縮排"],
 "Paragraph.Indent.Decrease": ["Decrease indent", "インデントを減らす", "내어쓰기", "减少缩进", "減少縮排"],
 "Paragraph.Indent.Increase": ["Increase indent", "インデントを増やす", "들여쓰기", "增加缩进", "增加縮排"],
 "Paragraph.LineSpacing": ["Line Spacing", "行間", "줄 간격", "行距", "行距"],
 "Paragraph.Numbering": ["Numbering", "段落番号", "번호 매기기", "编号", "編號"],
 "Paragraph.Section.Alignment": ["Alignment and Lists", "配置とリスト", "정렬 및 목록", "对齐与列表", "對齊與清單"],
 "Paragraph.Section.Spacing": ["Spacing", "間隔", "간격", "间距", "間距"],
 "Paragraph.Section.Style": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Paragraph.SpacingAfter": ["After: %lld pt", "段落後：%lld pt", "단락 뒤: %lldpt", "段后：%lld 磅", "段落後：%lld 點"],
 "Paragraph.SpacingBefore": ["Before: %lld pt", "段落前：%lld pt", "단락 앞: %lldpt", "段前：%lld 磅", "段落前：%lld 點"],
 "Style.Body": ["Body", "本文", "본문", "正文", "內文"],
 "Style.Heading1": ["Heading 1", "見出し 1", "제목 1", "标题 1", "標題 1"],
 "Style.Heading2": ["Heading 2", "見出し 2", "제목 2", "标题 2", "標題 2"],
 "Style.Heading3": ["Heading 3", "見出し 3", "제목 3", "标题 3", "標題 3"],
 "Style.Quote": ["Quote", "引用文", "인용", "引用", "引文"],
 "Style.Subtitle": ["Subtitle", "副題", "부제", "副标题", "副標題"],
 "Style.Title": ["Title", "表題", "제목", "标题", "標題"],
 "Table.AddColumn": ["Add Column", "列を追加", "열 추가", "添加列", "新增欄"],
 "Table.AddRow": ["Add Row", "行を追加", "행 추가", "添加行", "新增列"],
 "Table.Cell.Placeholder": ["Column %lld", "%lld列目", "%lld열", "第 %lld 列", "第 %lld 欄"],
 "Table.None": ["No Table Selected", "表が選択されていません", "선택된 표 없음", "未选择表格", "未選取表格"],
 "Table.RemoveColumn": ["Remove Last Column", "最後の列を削除", "마지막 열 제거", "移除最后一列", "移除最後一欄"],
 "Table.RemoveRow": ["Remove Last Row", "最後の行を削除", "마지막 행 제거", "移除最后一行", "移除最後一列"],
 "Table.Row": ["Row %lld", "%lld行目", "%lld행", "第 %lld 行", "第 %lld 列"],
 "Toolbar.Share.Label": ["Share Document", "書類を共有", "문서 공유", "共享文稿", "分享文件"],
 "Toolbar.ViewMode": ["View", "表示", "보기", "视图", "顯示方式"],
 "Undo.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Undo.Formatting": ["Formatting", "書式設定", "서식", "格式", "格式"],
 "Undo.Insertion": ["Insert", "挿入", "삽입", "插入", "插入"],
 "Undo.List": ["List", "リスト", "목록", "列表", "清單"],
 "Undo.PageSetup": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "Undo.ParagraphStyle": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Undo.Table": ["Table", "表", "표", "表格", "表格"],
 "Undo.Typing": ["Typing", "入力", "입력", "键入", "輸入"],
 "Unsupported.Comments": ["Comments", "コメント", "메모", "批注", "註解"],
 "Unsupported.ContentControls": ["Content controls, such as a table of contents", "目次などのコンテンツコントロール", "목차 등의 콘텐츠 컨트롤", "内容控件，例如目录", "內容控制項，例如目錄"],
 "Unsupported.EmbeddedObjects": ["Embedded objects", "埋め込みオブジェクト", "포함된 개체", "嵌入的对象", "內嵌物件"],
 "Unsupported.Equations": ["Equations", "数式", "수식", "公式", "方程式"],
 "Unsupported.Footnotes": ["Footnotes and endnotes", "脚注と文末脚注", "각주 및 미주", "脚注和尾注", "註腳和章節附註"],
 "Unsupported.Macros": ["Macros, which are kept but never run", "マクロ（保持されますが実行されません）", "매크로(유지되지만 실행되지 않음)", "宏（会保留，但绝不运行）", "巨集（會保留，但絕不執行）"],
 "Unsupported.Sections": ["Several sections: every page uses the last one’s setup", "複数のセクション（すべてのページに最後のセクションの設定を使用）", "여러 구역: 모든 페이지에 마지막 구역의 설정 사용", "多个分节：所有页面使用最后一节的设置", "多個章節：所有頁面使用最後一節的設定"],
 "Unsupported.Shapes": ["Shapes and text boxes", "図形とテキストボックス", "도형 및 텍스트 상자", "形状和文本框", "形狀和文字方塊"],
 "Unsupported.TrackedChanges": ["Tracked changes", "変更履歴", "변경 내용 추적", "修订", "追蹤修訂"],
 "ViewMode.Mobile": ["Mobile View", "モバイル表示", "모바일 보기", "移动视图", "行動版顯示"],
 "ViewMode.Page": ["Full Document", "ドキュメント全体", "전체 문서", "完整文稿", "完整文件"],
 "Toolbar.SourceCode": ["Source Code", "ソースコード", "소스 코드", "源代码", "原始碼"],
 "Toolbar.Find": ["Find and Replace", "検索と置換", "찾기 및 대치", "查找和替换", "尋找與取代"],
 "Format.Font": ["Font", "フォント", "서체", "字体", "字體"],
 "Font.Default": ["Default", "デフォルト", "기본", "默认", "預設"],
 "Font.Section.Theme": ["Theme Fonts", "テーマのフォント", "테마 서체", "主题字体", "主題字體"],
 "Font.Section.Document": ["In This Document", "この書類内", "이 문서에서 사용", "此文稿中", "此文件中"],
 "Font.Section.All": ["All Fonts", "すべてのフォント", "모든 서체", "所有字体", "所有字體"],
 "Font.Theme.Body": ["Body (%@)", "本文 (%@)", "본문(%@)", "正文（%@）", "內文（%@）"],
 "Font.Theme.Headings": ["Headings (%@)", "見出し (%@)", "제목(%@)", "标题（%@）", "標題（%@）"],
 "Panel.Link.Title": ["Link", "リンク", "링크", "链接", "連結"],
 "Insert.Link": ["Link", "リンク", "링크", "链接", "連結"],
 "ActionBar.EditLink": ["Edit Link", "リンクを編集", "링크 편집", "编辑链接", "編輯連結"],
 "Link.Address": ["Address", "アドレス", "주소", "地址", "位址"],
 "Link.Text": ["Text to Show", "表示する文字列", "표시할 텍스트", "要显示的文本", "要顯示的文字"],
 "Link.Footer": ["A web address, an email address, or # and a bookmark’s name.", "Webアドレス、メールアドレス、または「#」とブックマーク名。", "웹 주소, 이메일 주소 또는 # 뒤에 책갈피 이름.", "网址、电子邮件地址，或 # 加书签名称。", "網址、電子郵件位址，或 # 加書籤名稱。"],
 "Link.Insert": ["Insert Link", "リンクを挿入", "링크 삽입", "插入链接", "插入連結"],
 "Link.Update": ["Update Link", "リンクを更新", "링크 업데이트", "更新链接", "更新連結"],
 "Link.Open": ["Open Link", "リンクを開く", "링크 열기", "打开链接", "打開連結"],
 "Link.Remove": ["Remove Link", "リンクを解除", "링크 제거", "移除链接", "移除連結"],
 "Panel.HeaderFooter.Title": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "Insert.HeaderFooter": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "Undo.HeaderFooter": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "HeaderFooter.DifferentFirstPage": ["Different First Page", "先頭ページのみ別指定", "첫 페이지를 다르게 지정", "首页不同", "第一頁不同"],
 "HeaderFooter.DifferentOddEven": ["Different Odd & Even Pages", "奇数/偶数ページ別指定", "홀수/짝수 페이지를 다르게 지정", "奇偶页不同", "奇偶頁不同"],
 "HeaderFooter.Pages": ["Pages", "ページ", "페이지", "页面", "頁面"],
 "HeaderFooter.AllPages": ["All Pages", "すべてのページ", "모든 페이지", "所有页面", "所有頁面"],
 "HeaderFooter.OddPages": ["Odd Pages", "奇数ページ", "홀수 페이지", "奇数页", "奇數頁"],
 "HeaderFooter.EvenPages": ["Even Pages", "偶数ページ", "짝수 페이지", "偶数页", "偶數頁"],
 "HeaderFooter.FirstPage": ["First Page", "先頭ページ", "첫 페이지", "首页", "第一頁"],
 "HeaderFooter.Header": ["Header", "ヘッダー", "머리글", "页眉", "頁首"],
 "HeaderFooter.Footer": ["Footer", "フッター", "바닥글", "页脚", "頁尾"],
 "HeaderFooter.Header.Placeholder": ["Header text", "ヘッダーのテキスト", "머리글 텍스트", "页眉文本", "頁首文字"],
 "HeaderFooter.Footer.Placeholder": ["Footer text", "フッターのテキスト", "바닥글 텍스트", "页脚文本", "頁尾文字"],
 "HeaderFooter.PageNumber": ["Page Number", "ページ番号", "페이지 번호", "页码", "頁碼"],
 "HeaderFooter.PageCount": ["Page Count", "総ページ数", "총 페이지 수", "总页数", "總頁數"],
 "HeaderFooter.Fields": ["{PAGE} shows the page number, and {NUMPAGES} the number of pages.", "{PAGE}はページ番号、{NUMPAGES}は総ページ数になります。", "{PAGE}는 페이지 번호로, {NUMPAGES}는 총 페이지 수로 표시됩니다.", "{PAGE} 显示页码，{NUMPAGES} 显示总页数。", "{PAGE} 會顯示頁碼，{NUMPAGES} 會顯示總頁數。"],
 "HeaderFooter.RichContent": ["This one has pictures or tables, which editing its text replaces.", "このヘッダー/フッターには画像や表が含まれています。テキストを編集すると置き換えられます。", "이 머리글/바닥글에는 사진이나 표가 있으며, 텍스트를 편집하면 대치됩니다.", "其中包含图片或表格，编辑文本会将其替换。", "其中包含圖片或表格，編輯文字會將其取代。"],
 "Common.Cancel": ["Cancel", "キャンセル", "취소", "取消", "取消"],
 "Panel.Comments.Title": ["Comments", "コメント", "메모", "批注", "註解"],
 "Toolbar.Comments": ["Comments", "コメント", "메모", "批注", "註解"],
 "Insert.Comment": ["Comment", "コメント", "메모", "批注", "註解"],
 "ActionBar.ShowComments": ["Show Comments", "コメントを表示", "메모 보기", "显示批注", "顯示註解"],
 "Undo.Comment": ["Comment", "コメント", "메모", "批注", "註解"],
 "Comment.DefaultAuthor": ["Author", "作成者", "작성자", "作者", "作者"],
 "Comments.New.Placeholder": ["New comment", "新しいコメント", "새로운 메모", "新批注", "新增註解"],
 "Comments.New.Footer": ["Goes on the selected text, or the word at the cursor.", "選択したテキスト、またはカーソル位置の単語に付きます。", "선택한 텍스트나 커서 위치의 단어에 추가됩니다.", "添加到所选文本或光标处的单词。", "加到所選文字或游標處的字詞。"],
 "Comments.Add": ["Add Comment", "コメントを追加", "메모 추가", "添加批注", "加入註解"],
 "Comments.None": ["No Comments", "コメントなし", "메모 없음", "无批注", "沒有註解"],
 "Comments.YourName": ["Your Name", "あなたの名前", "사용자 이름", "你的姓名", "你的名稱"],
 "Comments.YourName.Placeholder": ["Name", "名前", "이름", "姓名", "名稱"],
 "Comments.YourName.Footer": ["Shown on your comments and tracked changes.", "コメントと変更履歴に表示されます。", "메모와 변경 내용 추적에 표시됩니다.", "显示在你的批注和修订中。", "顯示在你的註解和追蹤修訂中。"],
 "Comments.Edit.Placeholder": ["Comment", "コメント", "메모", "批注", "註解"],
 "Comments.Save": ["Save", "保存", "저장", "存储", "儲存"],
 "Comments.Resolved": ["Resolved", "解決済み", "해결됨", "已解决", "已解決"],
 "Comments.Reply": ["Reply", "返信", "회신", "回复", "回覆"],
 "Comments.Reply.Placeholder": ["Reply", "返信", "회신", "回复", "回覆"],
 "Comments.Resolve": ["Resolve", "解決", "해결", "解决", "解決"],
 "Comments.Reopen": ["Reopen", "もう一度開く", "다시 열기", "重新打开", "重新打開"],
 "Comments.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Comments.Delete": ["Delete", "削除", "삭제", "删除", "刪除"],
 "Comments.Actions": ["Comment Actions", "コメントの操作", "메모 동작", "批注操作", "註解動作"],
 "Panel.Review.Title": ["Review", "校閲", "검토", "审阅", "校閱"],
 "Toolbar.Review": ["Track Changes", "変更履歴", "변경 내용 추적", "修订", "追蹤修訂"],
 "Undo.Review": ["Review", "校閲", "검토", "审阅", "校閱"],
 "Review.TrackChanges": ["Track Changes", "変更履歴の記録", "변경 내용 추적", "修订", "追蹤修訂"],
 "Review.TrackChanges.Footer": ["Insertions are underlined and deletions struck through, in each reviewer’s colour, until they’re accepted or rejected.", "挿入は下線、削除は取り消し線で、校閲者ごとの色で表示されます。承諾または元に戻すまで残ります。", "삽입된 내용은 밑줄로, 삭제된 내용은 취소선으로 검토자마다 다른 색으로 표시되며, 승인하거나 거부할 때까지 유지됩니다.", "插入内容加下划线、删除内容加删除线，以各审阅者的颜色显示，直到接受或拒绝。", "插入的內容加底線、刪除的內容加刪除線，以各校閱者的顏色顯示，直到接受或拒絕。"],
 "Review.Section.Changes": ["Changes", "変更箇所", "변경 내용", "修订", "修訂"],
 "Review.Count": ["%d Changes", "%d件の変更", "변경 내용 %d개", "%d 处修订", "%d 處修訂"],
 "Review.Previous": ["Previous Change", "前の変更箇所", "이전 변경 내용", "上一处修订", "上一處修訂"],
 "Review.Next": ["Next Change", "次の変更箇所", "다음 변경 내용", "下一处修订", "下一處修訂"],
 "Review.Accept": ["Accept", "承諾", "승인", "接受", "接受"],
 "Review.Reject": ["Reject", "元に戻す", "거부", "拒绝", "拒絕"],
 "Review.AcceptAll": ["Accept All Changes", "すべての変更を承諾", "모든 변경 내용 승인", "接受所有修订", "接受所有修訂"],
 "Review.RejectAll": ["Reject All Changes", "すべての変更を元に戻す", "모든 변경 내용 거부", "拒绝所有修订", "拒絕所有修訂"],
 "Panel.Notes.Title": ["Footnotes & Endnotes", "脚注と文末脚注", "각주 및 미주", "脚注和尾注", "註腳和章節附註"],
 "Toolbar.Notes": ["Footnotes & Endnotes", "脚注と文末脚注", "각주 및 미주", "脚注和尾注", "註腳和章節附註"],
 "Undo.Notes": ["Notes", "脚注", "각주", "注释", "註腳"],
 "Insert.Footnote": ["Footnote", "脚注", "각주", "脚注", "註腳"],
 "Insert.Endnote": ["Endnote", "文末脚注", "미주", "尾注", "章節附註"],
 "Notes.InsertFootnote": ["Insert Footnote", "脚注を挿入", "각주 삽입", "插入脚注", "插入註腳"],
 "Notes.InsertEndnote": ["Insert Endnote", "文末脚注を挿入", "미주 삽입", "插入尾注", "插入章節附註"],
 "Notes.Insert.Footer": ["Goes in at the cursor.", "カーソル位置に挿入されます。", "커서 위치에 삽입됩니다.", "插入到光标处。", "插入到游標處。"],
 "Notes.Footnotes": ["Footnotes", "脚注", "각주", "脚注", "註腳"],
 "Notes.Endnotes": ["Endnotes", "文末脚注", "미주", "尾注", "章節附註"],
 "Notes.None": ["No Footnotes or Endnotes", "脚注・文末脚注なし", "각주 또는 미주 없음", "无脚注或尾注", "沒有註腳或章節附註"],
 "Notes.Placeholder": ["Note text", "脚注の内容", "각주 텍스트", "注释文本", "註腳文字"],
 "Notes.GoToReference": ["Go to Reference", "参照箇所へ移動", "참조로 이동", "转到引用", "前往參照"],
 "Notes.Actions": ["Note Actions", "脚注の操作", "각주 동작", "注释操作", "註腳動作"],
 "Format.Section.Effects": ["Effects", "文字飾り", "효과", "效果", "效果"],
 "Format.Underline": ["Underline", "下線", "밑줄", "下划线", "底線"],
 "Underline.none": ["None", "なし", "없음", "无", "無"],
 "Underline.single": ["Single", "一重線", "한 줄", "单线", "單線"],
 "Underline.double": ["Double", "二重線", "이중선", "双线", "雙線"],
 "Underline.thick": ["Thick", "太線", "굵은 선", "粗线", "粗線"],
 "Underline.dotted": ["Dotted", "点線", "점선", "点线", "點線"],
 "Underline.dash": ["Dashed", "破線", "파선", "虚线", "虛線"],
 "Underline.dotDash": ["Dot Dash", "一点鎖線", "일점 쇄선", "点划线", "點虛線"],
 "Underline.wave": ["Wavy", "波線", "물결선", "波浪线", "波浪線"],
 "Underline.words": ["Words Only", "単語のみ", "단어만", "仅字词", "僅字詞"],
 "Format.DoubleStrikethrough": ["Double Strikethrough", "二重取り消し線", "이중 취소선", "双删除线", "雙刪除線"],
 "Format.SmallCaps": ["Small Caps", "小型英大文字", "작은 대문자", "小型大写字母", "小型大寫字母"],
 "Format.AllCaps": ["All Caps", "すべて大文字", "모두 대문자", "全部大写", "全部大寫"],
 "Format.Outline": ["Outline", "中抜き", "윤곽선", "空心", "外框"],
 "Format.Shadow": ["Shadow", "影付き", "그림자", "阴影", "陰影"],
 "Format.Emboss": ["Emboss", "浮き出し", "양각", "阳文", "浮凸"],
 "Format.Engrave": ["Engrave", "浮き彫り", "음각", "阴文", "凹陷"],
 "Format.Spacing.Normal": ["Character Spacing: Normal", "文字間隔：標準", "문자 간격: 보통", "字符间距：标准", "字元間距：標準"],
 "Format.Spacing.Expanded": ["Character Spacing: %@ pt Wider", "文字間隔：%@ pt 広く", "문자 간격: %@pt 넓게", "字符间距：加宽 %@ 磅", "字元間距：加寬 %@ 點"],
 "Format.Spacing.Condensed": ["Character Spacing: %@ pt Narrower", "文字間隔：%@ pt 狭く", "문자 간격: %@pt 좁게", "字符间距：紧缩 %@ 磅", "字元間距：緊縮 %@ 點"],
 "Format.Position.Normal": ["Position: Normal", "位置：標準", "위치: 보통", "位置：标准", "位置：標準"],
 "Format.Position.Raised": ["Position: Raised %@ pt", "位置：%@ pt 上げる", "위치: %@pt 올림", "位置：提升 %@ 磅", "位置：提高 %@ 點"],
 "Format.Position.Lowered": ["Position: Lowered %@ pt", "位置：%@ pt 下げる", "위치: %@pt 내림", "位置：降低 %@ 磅", "位置：降低 %@ 點"],
 "Paragraph.Section.Pagination": ["Line and Page Breaks", "改ページと改行", "줄 및 페이지 나누기", "换行和分页", "分行與分頁"],
 "Paragraph.KeepWithNext": ["Keep with Next", "次の段落と分離しない", "다음 단락과 함께", "与下段同页", "與下段同頁"],
 "Paragraph.KeepLinesTogether": ["Keep Lines Together", "段落を分割しない", "현재 단락을 나누지 않음", "段中不分页", "段中不分頁"],
 "Paragraph.WidowControl": ["Widow Control", "改ページ時1行残して段落を区切らない", "페이지 나누기 시 한 줄 남기지 않음", "孤行控制", "遺留字串控制"],
 "Paragraph.PageBreakBefore": ["Page Break Before", "段落前で改ページする", "단락 앞에서 페이지 나누기", "段前分页", "段落前分頁"],
 "Paragraph.Section.Borders": ["Borders & Shading", "罫線と網かけ", "테두리 및 음영", "边框和底纹", "框線及網底"],
 "Paragraph.Borders": ["Borders", "罫線", "테두리", "边框", "框線"],
 "Paragraph.Borders.none": ["None", "なし", "없음", "无", "無"],
 "Paragraph.Borders.box": ["Box", "囲む", "상자", "方框", "方框"],
 "Paragraph.Borders.top": ["Top", "上", "위쪽", "上框线", "上框線"],
 "Paragraph.Borders.bottom": ["Bottom", "下", "아래쪽", "下框线", "下框線"],
 "Paragraph.Borders.topAndBottom": ["Top & Bottom", "上下", "위쪽 및 아래쪽", "上下框线", "上下框線"],
 "Paragraph.Borders.sides": ["Left & Right", "左右", "왼쪽 및 오른쪽", "左右框线", "左右框線"],
 "Paragraph.Borders.Custom": ["Custom", "カスタム", "사용자 지정", "自定", "自訂"],
 "Paragraph.BorderStyle": ["Line", "線種", "선", "线型", "線條"],
 "Border.single": ["Single", "実線", "실선", "单实线", "單線"],
 "Border.double": ["Double", "二重線", "이중선", "双线", "雙線"],
 "Border.dotted": ["Dotted", "点線", "점선", "点线", "點線"],
 "Border.dashed": ["Dashed", "破線", "파선", "虚线", "虛線"],
 "Border.thick": ["Thick", "太線", "굵은 선", "粗线", "粗線"],
 "Paragraph.Shading": ["Shading", "網かけ", "음영", "底纹", "網底"],
 "Paragraph.Section.Tabs": ["Tab Stops", "タブ位置", "탭 정지", "制表位", "定位點"],
 "Paragraph.Tabs.Footer": ["From the left margin.", "左余白からの位置です。", "왼쪽 여백에서부터의 위치입니다.", "从左边距算起。", "從左邊界算起。"],
 "Paragraph.AddTab": ["Add Tab Stop", "タブ位置を追加", "탭 정지 추가", "添加制表位", "加入定位點"],
 "Paragraph.RemoveTab": ["Remove Tab Stop", "タブ位置を削除", "탭 정지 제거", "删除制表位", "移除定位點"],
 "Paragraph.Tab.Alignment": ["Alignment", "配置", "정렬", "对齐方式", "對齊方式"],
 "Paragraph.Tab.Leader": ["Leader", "リーダー", "채움선", "前导符", "前置字元"],
 "Tab.left": ["Left", "左揃え", "왼쪽", "左对齐", "靠左"],
 "Tab.center": ["Center", "中央揃え", "가운데", "居中", "置中"],
 "Tab.right": ["Right", "右揃え", "오른쪽", "右对齐", "靠右"],
 "Tab.decimal": ["Decimal", "小数点揃え", "소수점", "小数点对齐", "小數點"],
 "Leader.none": ["No Leader", "リーダーなし", "채움선 없음", "无前导符", "無前置字元"],
 "Leader.dot": ["Dots", "点線", "점", "点", "點"],
 "Leader.hyphen": ["Dashes", "ハイフン", "대시", "短划线", "虛線"],
 "Leader.underscore": ["Line", "下線", "선", "下划线", "底線"],
 "Paragraph.Section.DropCap": ["Drop Cap", "ドロップキャップ", "단락 첫 문자 장식", "首字下沉", "首字放大"],
 "Paragraph.DropCap": ["Drop Cap", "ドロップキャップ", "단락 첫 문자 장식", "首字下沉", "首字放大"],
 "DropCap.none": ["None", "なし", "없음", "无", "無"],
 "DropCap.drop": ["Dropped", "本文内に表示", "본문", "下沉", "繞排"],
 "DropCap.margin": ["In Margin", "余白に表示", "여백", "悬挂", "邊界"],
 "Paragraph.DropCap.Lines": ["Lines to Drop: %d", "ドロップする行数：%d", "놓을 줄 수: %d", "下沉行数：%d", "放大行數：%d"],
 "List.Title": ["Bullets & Numbering", "箇条書きと段落番号", "글머리 기호 및 번호 매기기", "项目符号和编号", "項目符號及編號"],
 "List.Section.Bullets": ["Bullets", "箇条書き", "글머리 기호", "项目符号", "項目符號"],
 "List.Section.Numbering": ["Numbering", "段落番号", "번호 매기기", "编号", "編號"],
 "List.Section.Multilevel": ["Multilevel", "アウトライン", "다단계", "多级列表", "多層次清單"],
 "List.Section.Numbers": ["Numbering Value", "番号の値", "번호 값", "编号值", "編號值"],
 "List.StartAt": ["Start At: %d", "開始番号：%d", "시작 번호: %d", "起始编号：%d", "起始值：%d"],
 "List.Restart": ["Restart Numbering", "番号を振り直す", "번호 다시 매기기", "重新开始编号", "重新編號"],
 "List.Continue": ["Continue Numbering", "番号を継続する", "번호 계속 매기기", "继续编号", "繼續編號"],
}

reuse = ["Alert.Error.Title", "Common.OK", "Format.ClearAll", "Format.Section.Text", "Format.Text.Size",
         "Format.Text.Size.Decrease", "Format.Text.Size.Increase", "Toolbar.Bold", "Toolbar.Italic",
         "Toolbar.Redo", "Toolbar.Strikethrough", "Toolbar.Underline", "Toolbar.Undo",
         "Toolbar.UnsupportedFeatures.Label", "ColorSwatches.More.Text.Accessibility", "ColorSwatches.MoreColours",
         "ColorSwatches.None.Text.Accessibility", "ColorSwatches.Swatch.Text.Accessibility",
         "ColorSwatches.More.Fill.Accessibility", "ColorSwatches.None.Fill.Accessibility",
         "ColorSwatches.Swatch.Fill.Accessibility", "ColorSwatches.More.Border.Accessibility",
         "ColorSwatches.None.Border.Accessibility", "ColorSwatches.Swatch.Border.Accessibility"]
reuse += [k for k in ["Color.Black", "Color.Blue", "Color.Brown", "Color.Cyan", "Color.Green", "Color.Grey",
          "Color.Grey2", "Color.Grey3", "Color.Grey4", "Color.Grey5", "Color.Grey6", "Color.Indigo", "Color.Mint",
          "Color.Orange", "Color.Pink", "Color.Purple", "Color.Red", "Color.Teal", "Color.White", "Color.Yellow"]]

tables = json.load(open(tables_path))["strings"]
strings = {}
for key, values in S.items():
    strings[key] = {"extractionState": "manual", "localizations": {
        lang: {"stringUnit": {"state": "translated", "value": value}} for lang, value in zip(LANGS, values)}}
for key in reuse:
    if key not in tables:
        sys.exit(f"Tables has no {key}")
    entry = dict(tables[key])
    entry["extractionState"] = "manual"
    strings[key] = entry
    missing = [lang for lang in LANGS if lang not in entry.get("localizations", {})]
    if missing:
        sys.exit(f"{key} lacks {missing}")

catalog = {"sourceLanguage": "en", "strings": dict(sorted(strings.items())), "version": "1.0"}
with open(out_path, "w") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print(len(strings), "strings")
