"""Builds Libretto's string catalog. Keys Tables already translates reuse its
translations, so the two apps speak the same words for the same things."""
import json, sys, os

LANGS = ["en", "ja", "ko", "zh-Hans", "zh-Hant"]
here = os.path.dirname(os.path.abspath(__file__))
tables_path = os.path.join(here, "..", "..", "Tables", "Tables", "Support", "Localizable.xcstrings")
out_path = os.path.join(here, "..", "Libretto", "Support", "Localizable.xcstrings")

S = {
 "ActionBar.Alignment": ["Alignment", "配置", "정렬", "对齐", "對齊"],
 "ActionBar.Bullets": ["Bulleted List", "箇条書き", "글머리 기호 목록", "项目符号列表", "項目符號清單"],
 "ActionBar.DeleteTable": ["Delete Table", "表を削除", "표 삭제", "删除表格", "刪除表格"],
 "ActionBar.EditTable": ["Edit Table", "表を編集", "표 편집", "编辑表格", "編輯表格"],
 "ActionBar.Format": ["Format", "書式", "서식", "格式", "格式"],
 "ActionBar.Insert": ["Insert", "挿入", "삽입", "插入", "插入"],
 "ActionBar.Numbering": ["Numbered List", "段落番号", "번호 매기기 목록", "编号列表", "編號清單"],
 "ActionBar.PageSetup": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "ActionBar.Paragraph": ["Paragraph", "段落", "단락", "段落", "段落"],
 "ActionBar.Style": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Alert.Picture.Failed": ["The picture couldn’t be loaded.", "画像を読み込めませんでした。", "사진을 불러올 수 없습니다.", "无法载入图片。", "無法載入圖片。"],
 "Alignment.Center": ["Center", "中央揃え", "가운데 정렬", "居中", "置中"],
 "Alignment.Justified": ["Justified", "両端揃え", "양쪽 정렬", "两端对齐", "左右對齊"],
 "Alignment.Left": ["Left", "左揃え", "왼쪽 정렬", "左对齐", "靠左對齊"],
 "Alignment.Right": ["Right", "右揃え", "오른쪽 정렬", "右对齐", "靠右對齊"],
 "Block.Preserved.Placeholder": ["Content Libretto can’t show", "Librettoで表示できないコンテンツ", "Libretto에서 표시할 수 없는 콘텐츠", "Libretto 无法显示的内容", "Libretto 無法顯示的內容"],
 "Document.DefaultName": ["Document", "書類", "문서", "文稿", "文件"],
 "Error.MissingBody": ["This document has no body to show.", "この書類には表示できる本文がありません。", "이 문서에는 표시할 본문이 없습니다.", "此文稿没有可显示的正文。", "此文件沒有可顯示的內文。"],
 "Error.MissingMainDocument": ["This file isn’t a Word document.", "このファイルはWord書類ではありません。", "이 파일은 Word 문서가 아닙니다.", "此文件不是 Word 文稿。", "此檔案不是 Word 文件。"],
 "Format.Section.Highlight": ["Highlight", "蛍光ペン", "형광펜", "突出显示", "螢光筆"],
 "Format.Subscript": ["Subscript", "下付き", "아래 첨자", "下标", "下標"],
 "Format.Superscript": ["Superscript", "上付き", "위 첨자", "上标", "上標"],
 "Highlight.None": ["No highlight", "蛍光ペンなし", "형광펜 없음", "无突出显示", "無螢光筆"],
 "Highlight.yellow": ["Yellow highlight", "黄色の蛍光ペン", "노란색 형광펜", "黄色突出显示", "黃色螢光筆"],
 "Highlight.green": ["Green highlight", "緑の蛍光ペン", "초록색 형광펜", "绿色突出显示", "綠色螢光筆"],
 "Highlight.cyan": ["Turquoise highlight", "水色の蛍光ペン", "청록색 형광펜", "青绿色突出显示", "青綠色螢光筆"],
 "Highlight.magenta": ["Pink highlight", "ピンクの蛍光ペン", "분홍색 형광펜", "粉红色突出显示", "粉紅色螢光筆"],
 "Highlight.red": ["Red highlight", "赤の蛍光ペン", "빨간색 형광펜", "红色突出显示", "紅色螢光筆"],
 "Highlight.blue": ["Blue highlight", "青の蛍光ペン", "파란색 형광펜", "蓝色突出显示", "藍色螢光筆"],
 "Highlight.lightGray": ["Grey highlight", "灰色の蛍光ペン", "회색 형광펜", "灰色突出显示", "灰色螢光筆"],
 "Highlight.darkYellow": ["Dark yellow highlight", "濃い黄色の蛍光ペン", "진한 노란색 형광펜", "深黄色突出显示", "深黃色螢光筆"],
 "Launch.NewDocument": ["Create Document", "書類を作成", "문서 만들기", "创建文稿", "建立文件"],
 "Insert.PageBreak": ["Page Break", "改ページ", "페이지 나누기", "分页符", "分頁符號"],
 "Insert.Picture": ["Picture…", "画像…", "사진…", "图片…", "圖片…"],
 "Insert.Table": ["Table…", "表…", "표…", "表格…", "表格…"],
 "InsertTable.Columns": ["Columns: %lld", "列：%lld", "열: %lld", "列：%lld", "欄：%lld"],
 "InsertTable.Insert": ["Insert Table", "表を挿入", "표 삽입", "插入表格", "插入表格"],
 "InsertTable.Rows": ["Rows: %lld", "行：%lld", "행: %lld", "行：%lld", "列：%lld"],
 "Mobile.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Mobile.Picture": ["Picture", "画像", "사진", "图片", "圖片"],
 "Mobile.WordCount": ["%lld words", "%lld語", "%lld단어", "%lld 个词", "%lld 個字詞"],
 "Notice.UnsupportedFeatures.Message": ["This document uses things Libretto can show but not edit. They’re kept as they are, and saved back with the document. Libretto never runs macros.", "この書類には、Librettoで表示はできても編集できない要素が含まれています。これらはそのまま保持され、書類と一緒に保存されます。Librettoがマクロを実行することはありません。", "이 문서에는 Libretto에서 표시할 수는 있지만 편집할 수 없는 요소가 있습니다. 이러한 요소는 그대로 유지되며 문서와 함께 저장됩니다. Libretto는 매크로를 실행하지 않습니다.", "此文稿包含 Libretto 可以显示但无法编辑的内容。这些内容会原样保留，并随文稿一起存储。Libretto 绝不会运行宏。", "此文件包含 Libretto 可以顯示但無法編輯的內容。這些內容會原樣保留，並隨文件一起儲存。Libretto 絕不會執行巨集。"],
 "Notice.UnsupportedFeatures.Title": ["Some Parts Are Read-Only", "一部は読み取り専用です", "일부는 읽기 전용입니다", "部分内容为只读", "部分內容為唯讀"],
 "PageSetup.Landscape": ["Landscape", "横", "가로", "横向", "橫向"],
 "PageSetup.Margins.Description": ["Top and bottom %1$@, sides %2$@", "上下 %1$@、左右 %2$@", "위아래 %1$@, 양옆 %2$@", "上下 %1$@，左右 %2$@", "上下 %1$@，左右 %2$@"],
 "PageSetup.Margins.Moderate": ["Moderate", "やや狭い", "보통", "适中", "適中"],
 "PageSetup.Margins.Narrow": ["Narrow", "狭い", "좁게", "窄", "窄"],
 "PageSetup.Margins.Normal": ["Normal", "標準", "기본", "常规", "標準"],
 "PageSetup.Margins.Wide": ["Wide", "広い", "넓게", "宽", "寬"],
 "PageSetup.Orientation": ["Orientation", "向き", "방향", "方向", "方向"],
 "PageSetup.Paper": ["Paper Size", "用紙サイズ", "용지 크기", "纸张大小", "紙張大小"],
 "PageSetup.Paper.Custom": ["Custom (%.0f × %.0f mm)", "カスタム（%.0f × %.0f mm）", "사용자 지정(%.0f × %.0f mm)", "自定（%.0f × %.0f 毫米）", "自訂（%.0f × %.0f 公釐）"],
 "PageSetup.Paper.Legal": ["US Legal", "US リーガル", "US 리걸", "美国法律用纸", "美國法律用紙"],
 "PageSetup.Paper.Letter": ["US Letter", "US レター", "US 레터", "美国信纸", "美國信紙"],
 "PageSetup.Portrait": ["Portrait", "縦", "세로", "纵向", "直向"],
 "PageSetup.Section.Margins": ["Margins", "余白", "여백", "页边距", "邊界"],
 "PageSetup.Section.Paper": ["Paper", "用紙", "용지", "纸张", "紙張"],
 "Panel.Format.Title": ["Format", "書式", "서식", "格式", "格式"],
 "Panel.InsertTable.Title": ["Insert Table", "表を挿入", "표 삽입", "插入表格", "插入表格"],
 "Panel.PageSetup.Title": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "Panel.Paragraph.Title": ["Paragraph", "段落", "단락", "段落", "段落"],
 "Panel.Table.Title": ["Table", "表", "표", "表格", "表格"],
 "Paragraph.Alignment": ["Alignment", "配置", "정렬", "对齐", "對齊"],
 "Paragraph.Bullets": ["Bullets", "箇条書き", "글머리 기호", "项目符号", "項目符號"],
 "Paragraph.Indent": ["Indent", "インデント", "들여쓰기", "缩进", "縮排"],
 "Paragraph.Indent.Decrease": ["Decrease indent", "インデントを減らす", "내어쓰기", "减少缩进", "減少縮排"],
 "Paragraph.Indent.Increase": ["Increase indent", "インデントを増やす", "들여쓰기", "增加缩进", "增加縮排"],
 "Paragraph.LineSpacing": ["Line Spacing", "行間", "줄 간격", "行距", "行距"],
 "Paragraph.Numbering": ["Numbering", "段落番号", "번호 매기기", "编号", "編號"],
 "Paragraph.Section.Alignment": ["Alignment and Lists", "配置とリスト", "정렬 및 목록", "对齐与列表", "對齊與清單"],
 "Paragraph.Section.Spacing": ["Spacing", "間隔", "간격", "间距", "間距"],
 "Paragraph.Section.Style": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Paragraph.SpacingAfter": ["After: %lld pt", "段落後：%lld pt", "단락 뒤: %lldpt", "段后：%lld 磅", "段落後：%lld 點"],
 "Paragraph.SpacingBefore": ["Before: %lld pt", "段落前：%lld pt", "단락 앞: %lldpt", "段前：%lld 磅", "段落前：%lld 點"],
 "Style.Body": ["Body", "本文", "본문", "正文", "內文"],
 "Style.Heading1": ["Heading 1", "見出し 1", "제목 1", "标题 1", "標題 1"],
 "Style.Heading2": ["Heading 2", "見出し 2", "제목 2", "标题 2", "標題 2"],
 "Style.Heading3": ["Heading 3", "見出し 3", "제목 3", "标题 3", "標題 3"],
 "Style.Quote": ["Quote", "引用文", "인용", "引用", "引文"],
 "Style.Subtitle": ["Subtitle", "副題", "부제", "副标题", "副標題"],
 "Style.Title": ["Title", "表題", "제목", "标题", "標題"],
 "Table.None": ["No Table Selected", "表が選択されていません", "선택된 표 없음", "未选择表格", "未選取表格"],
 "Toolbar.Share.Label": ["Share Document", "書類を共有", "문서 공유", "共享文稿", "分享文件"],
 "Toolbar.ViewMode": ["View", "表示", "보기", "视图", "顯示方式"],
 "Undo.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Undo.Formatting": ["Formatting", "書式設定", "서식", "格式", "格式"],
 "Undo.Insertion": ["Insert", "挿入", "삽입", "插入", "插入"],
 "Undo.List": ["List", "リスト", "목록", "列表", "清單"],
 "Undo.PageSetup": ["Page Setup", "ページ設定", "페이지 설정", "页面设置", "版面設定"],
 "Undo.ParagraphStyle": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Undo.Table": ["Table", "表", "표", "表格", "表格"],
 "Undo.Typing": ["Typing", "入力", "입력", "键入", "輸入"],
 "Unsupported.ContentControls": ["Content controls, such as a table of contents", "目次などのコンテンツコントロール", "목차 등의 콘텐츠 컨트롤", "内容控件，例如目录", "內容控制項，例如目錄"],
 "Unsupported.EmbeddedObjects": ["Embedded objects", "埋め込みオブジェクト", "포함된 개체", "嵌入的对象", "內嵌物件"],
 "Unsupported.Macros": ["Macros, which are kept but never run", "マクロ（保持されますが実行されません）", "매크로(유지되지만 실행되지 않음)", "宏（会保留，但绝不运行）", "巨集（會保留，但絕不執行）"],
 "Unsupported.Shapes": ["Shapes and text boxes", "図形とテキストボックス", "도형 및 텍스트 상자", "形状和文本框", "形狀和文字方塊"],
 "ViewMode.Mobile": ["Mobile View", "モバイル表示", "모바일 보기", "移动视图", "行動版顯示"],
 "ViewMode.Page": ["Full Document", "ドキュメント全体", "전체 문서", "完整文稿", "完整文件"],
 "Toolbar.SourceCode": ["Source Code", "ソースコード", "소스 코드", "源代码", "原始碼"],
 "Toolbar.Find": ["Find and Replace", "検索と置換", "찾기 및 대치", "查找和替换", "尋找與取代"],
 "Format.Font": ["Font", "フォント", "서체", "字体", "字體"],
 "Font.Default": ["Default", "デフォルト", "기본", "默认", "預設"],
 "Font.Section.Theme": ["Theme Fonts", "テーマのフォント", "테마 서체", "主题字体", "主題字體"],
 "Font.Section.Document": ["In This Document", "この書類内", "이 문서에서 사용", "此文稿中", "此文件中"],
 "Font.Section.All": ["All Fonts", "すべてのフォント", "모든 서체", "所有字体", "所有字體"],
 "Font.Theme.Body": ["Body (%@)", "本文 (%@)", "본문(%@)", "正文（%@）", "內文（%@）"],
 "Font.Theme.Headings": ["Headings (%@)", "見出し (%@)", "제목(%@)", "标题（%@）", "標題（%@）"],
 "Panel.Link.Title": ["Link", "リンク", "링크", "链接", "連結"],
 "Insert.Link": ["Link", "リンク", "링크", "链接", "連結"],
 "ActionBar.EditLink": ["Edit Link", "リンクを編集", "링크 편집", "编辑链接", "編輯連結"],
 "Link.Address": ["Address", "アドレス", "주소", "地址", "位址"],
 "Link.Text": ["Text to Show", "表示する文字列", "표시할 텍스트", "要显示的文本", "要顯示的文字"],
 "Link.Footer": ["A web address, an email address, or # and a bookmark’s name.", "Webアドレス、メールアドレス、または「#」とブックマーク名。", "웹 주소, 이메일 주소 또는 # 뒤에 책갈피 이름.", "网址、电子邮件地址，或 # 加书签名称。", "網址、電子郵件位址，或 # 加書籤名稱。"],
 "Link.Insert": ["Insert Link", "リンクを挿入", "링크 삽입", "插入链接", "插入連結"],
 "Link.Update": ["Update Link", "リンクを更新", "링크 업데이트", "更新链接", "更新連結"],
 "Link.Open": ["Open Link", "リンクを開く", "링크 열기", "打开链接", "打開連結"],
 "Link.Remove": ["Remove Link", "リンクを解除", "링크 제거", "移除链接", "移除連結"],
 "Panel.HeaderFooter.Title": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "Insert.HeaderFooter": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "Undo.HeaderFooter": ["Header & Footer", "ヘッダーとフッター", "머리글 및 바닥글", "页眉和页脚", "頁首和頁尾"],
 "HeaderFooter.DifferentFirstPage": ["Different First Page", "先頭ページのみ別指定", "첫 페이지를 다르게 지정", "首页不同", "第一頁不同"],
 "HeaderFooter.DifferentOddEven": ["Different Odd & Even Pages", "奇数/偶数ページ別指定", "홀수/짝수 페이지를 다르게 지정", "奇偶页不同", "奇偶頁不同"],
 "HeaderFooter.Pages": ["Pages", "ページ", "페이지", "页面", "頁面"],
 "HeaderFooter.AllPages": ["All Pages", "すべてのページ", "모든 페이지", "所有页面", "所有頁面"],
 "HeaderFooter.OddPages": ["Odd Pages", "奇数ページ", "홀수 페이지", "奇数页", "奇數頁"],
 "HeaderFooter.EvenPages": ["Even Pages", "偶数ページ", "짝수 페이지", "偶数页", "偶數頁"],
 "HeaderFooter.FirstPage": ["First Page", "先頭ページ", "첫 페이지", "首页", "第一頁"],
 "HeaderFooter.Header": ["Header", "ヘッダー", "머리글", "页眉", "頁首"],
 "HeaderFooter.Footer": ["Footer", "フッター", "바닥글", "页脚", "頁尾"],
 "HeaderFooter.Header.Placeholder": ["Header text", "ヘッダーのテキスト", "머리글 텍스트", "页眉文本", "頁首文字"],
 "HeaderFooter.Footer.Placeholder": ["Footer text", "フッターのテキスト", "바닥글 텍스트", "页脚文本", "頁尾文字"],
 "HeaderFooter.PageNumber": ["Page Number", "ページ番号", "페이지 번호", "页码", "頁碼"],
 "HeaderFooter.PageCount": ["Page Count", "総ページ数", "총 페이지 수", "总页数", "總頁數"],
 "HeaderFooter.Fields": ["{PAGE} shows the page number, and {NUMPAGES} the number of pages.", "{PAGE}はページ番号、{NUMPAGES}は総ページ数になります。", "{PAGE}는 페이지 번호로, {NUMPAGES}는 총 페이지 수로 표시됩니다.", "{PAGE} 显示页码，{NUMPAGES} 显示总页数。", "{PAGE} 會顯示頁碼，{NUMPAGES} 會顯示總頁數。"],
 "HeaderFooter.RichContent": ["This one has pictures or tables, which editing its text replaces.", "このヘッダー/フッターには画像や表が含まれています。テキストを編集すると置き換えられます。", "이 머리글/바닥글에는 사진이나 표가 있으며, 텍스트를 편집하면 대치됩니다.", "其中包含图片或表格，编辑文本会将其替换。", "其中包含圖片或表格，編輯文字會將其取代。"],
 "Common.Cancel": ["Cancel", "キャンセル", "취소", "取消", "取消"],
 "Panel.Comments.Title": ["Comments", "コメント", "메모", "批注", "註解"],
 "Toolbar.Comments": ["Comments", "コメント", "메모", "批注", "註解"],
 "Insert.Comment": ["Comment", "コメント", "메모", "批注", "註解"],
 "ActionBar.ShowComments": ["Show Comments", "コメントを表示", "메모 보기", "显示批注", "顯示註解"],
 "Undo.Comment": ["Comment", "コメント", "메모", "批注", "註解"],
 "Comment.DefaultAuthor": ["Author", "作成者", "작성자", "作者", "作者"],
 "Comments.New.Placeholder": ["New comment", "新しいコメント", "새로운 메모", "新批注", "新增註解"],
 "Comments.New.Footer": ["Goes on the selected text, or the word at the cursor.", "選択したテキスト、またはカーソル位置の単語に付きます。", "선택한 텍스트나 커서 위치의 단어에 추가됩니다.", "添加到所选文本或光标处的单词。", "加到所選文字或游標處的字詞。"],
 "Comments.Add": ["Add Comment", "コメントを追加", "메모 추가", "添加批注", "加入註解"],
 "Comments.None": ["No Comments", "コメントなし", "메모 없음", "无批注", "沒有註解"],
 "Comments.YourName": ["Your Name", "あなたの名前", "사용자 이름", "你的姓名", "你的名稱"],
 "Comments.YourName.Placeholder": ["Name", "名前", "이름", "姓名", "名稱"],
 "Comments.YourName.Footer": ["Shown on your comments and tracked changes.", "コメントと変更履歴に表示されます。", "메모와 변경 내용 추적에 표시됩니다.", "显示在你的批注和修订中。", "顯示在你的註解和追蹤修訂中。"],
 "Comments.Edit.Placeholder": ["Comment", "コメント", "메모", "批注", "註解"],
 "Comments.Save": ["Save", "保存", "저장", "存储", "儲存"],
 "Comments.Resolved": ["Resolved", "解決済み", "해결됨", "已解决", "已解決"],
 "Comments.Reply": ["Reply", "返信", "회신", "回复", "回覆"],
 "Comments.Reply.Placeholder": ["Reply", "返信", "회신", "回复", "回覆"],
 "Comments.Resolve": ["Resolve", "解決", "해결", "解决", "解決"],
 "Comments.Reopen": ["Reopen", "もう一度開く", "다시 열기", "重新打开", "重新打開"],
 "Comments.Edit": ["Edit", "編集", "편집", "编辑", "編輯"],
 "Comments.Delete": ["Delete", "削除", "삭제", "删除", "刪除"],
 "Comments.Actions": ["Comment Actions", "コメントの操作", "메모 동작", "批注操作", "註解動作"],
 "Panel.Review.Title": ["Review", "校閲", "검토", "审阅", "校閱"],
 "Toolbar.Review": ["Track Changes", "変更履歴", "변경 내용 추적", "修订", "追蹤修訂"],
 "Undo.Review": ["Review", "校閲", "검토", "审阅", "校閱"],
 "Review.TrackChanges": ["Track Changes", "変更履歴の記録", "변경 내용 추적", "修订", "追蹤修訂"],
 "Review.TrackChanges.Footer": ["Insertions are underlined and deletions struck through, in each reviewer’s colour, until they’re accepted or rejected.", "挿入は下線、削除は取り消し線で、校閲者ごとの色で表示されます。承諾または元に戻すまで残ります。", "삽입된 내용은 밑줄로, 삭제된 내용은 취소선으로 검토자마다 다른 색으로 표시되며, 승인하거나 거부할 때까지 유지됩니다.", "插入内容加下划线、删除内容加删除线，以各审阅者的颜色显示，直到接受或拒绝。", "插入的內容加底線、刪除的內容加刪除線，以各校閱者的顏色顯示，直到接受或拒絕。"],
 "Review.Section.Changes": ["Changes", "変更箇所", "변경 내용", "修订", "修訂"],
 "Review.Count": ["%d Changes", "%d件の変更", "변경 내용 %d개", "%d 处修订", "%d 處修訂"],
 "Review.Previous": ["Previous Change", "前の変更箇所", "이전 변경 내용", "上一处修订", "上一處修訂"],
 "Review.Next": ["Next Change", "次の変更箇所", "다음 변경 내용", "下一处修订", "下一處修訂"],
 "Review.Accept": ["Accept", "承諾", "승인", "接受", "接受"],
 "Review.Reject": ["Reject", "元に戻す", "거부", "拒绝", "拒絕"],
 "Review.AcceptAll": ["Accept All Changes", "すべての変更を承諾", "모든 변경 내용 승인", "接受所有修订", "接受所有修訂"],
 "Review.RejectAll": ["Reject All Changes", "すべての変更を元に戻す", "모든 변경 내용 거부", "拒绝所有修订", "拒絕所有修訂"],
 "Panel.Notes.Title": ["Footnotes & Endnotes", "脚注と文末脚注", "각주 및 미주", "脚注和尾注", "註腳和章節附註"],
 "Toolbar.Notes": ["Footnotes & Endnotes", "脚注と文末脚注", "각주 및 미주", "脚注和尾注", "註腳和章節附註"],
 "Undo.Notes": ["Notes", "脚注", "각주", "注释", "註腳"],
 "Insert.Footnote": ["Footnote", "脚注", "각주", "脚注", "註腳"],
 "Insert.Endnote": ["Endnote", "文末脚注", "미주", "尾注", "章節附註"],
 "Notes.InsertFootnote": ["Insert Footnote", "脚注を挿入", "각주 삽입", "插入脚注", "插入註腳"],
 "Notes.InsertEndnote": ["Insert Endnote", "文末脚注を挿入", "미주 삽입", "插入尾注", "插入章節附註"],
 "Notes.Insert.Footer": ["Goes in at the cursor.", "カーソル位置に挿入されます。", "커서 위치에 삽입됩니다.", "插入到光标处。", "插入到游標處。"],
 "Notes.Footnotes": ["Footnotes", "脚注", "각주", "脚注", "註腳"],
 "Notes.Endnotes": ["Endnotes", "文末脚注", "미주", "尾注", "章節附註"],
 "Notes.None": ["No Footnotes or Endnotes", "脚注・文末脚注なし", "각주 또는 미주 없음", "无脚注或尾注", "沒有註腳或章節附註"],
 "Notes.Placeholder": ["Note text", "脚注の内容", "각주 텍스트", "注释文本", "註腳文字"],
 "Notes.GoToReference": ["Go to Reference", "参照箇所へ移動", "참조로 이동", "转到引用", "前往參照"],
 "Notes.Actions": ["Note Actions", "脚注の操作", "각주 동작", "注释操作", "註腳動作"],
 "Format.Section.Effects": ["Effects", "文字飾り", "효과", "效果", "效果"],
 "Format.Underline": ["Underline", "下線", "밑줄", "下划线", "底線"],
 "Underline.none": ["None", "なし", "없음", "无", "無"],
 "Underline.single": ["Single", "一重線", "한 줄", "单线", "單線"],
 "Underline.double": ["Double", "二重線", "이중선", "双线", "雙線"],
 "Underline.thick": ["Thick", "太線", "굵은 선", "粗线", "粗線"],
 "Underline.dotted": ["Dotted", "点線", "점선", "点线", "點線"],
 "Underline.dash": ["Dashed", "破線", "파선", "虚线", "虛線"],
 "Underline.dotDash": ["Dot Dash", "一点鎖線", "일점 쇄선", "点划线", "點虛線"],
 "Underline.wave": ["Wavy", "波線", "물결선", "波浪线", "波浪線"],
 "Underline.words": ["Words Only", "単語のみ", "단어만", "仅字词", "僅字詞"],
 "Format.DoubleStrikethrough": ["Double Strikethrough", "二重取り消し線", "이중 취소선", "双删除线", "雙刪除線"],
 "Format.SmallCaps": ["Small Caps", "小型英大文字", "작은 대문자", "小型大写字母", "小型大寫字母"],
 "Format.AllCaps": ["All Caps", "すべて大文字", "모두 대문자", "全部大写", "全部大寫"],
 "Format.Outline": ["Outline", "中抜き", "윤곽선", "空心", "外框"],
 "Format.Shadow": ["Shadow", "影付き", "그림자", "阴影", "陰影"],
 "Format.Emboss": ["Emboss", "浮き出し", "양각", "阳文", "浮凸"],
 "Format.Engrave": ["Engrave", "浮き彫り", "음각", "阴文", "凹陷"],
 "Format.Spacing.Normal": ["Character Spacing: Normal", "文字間隔：標準", "문자 간격: 보통", "字符间距：标准", "字元間距：標準"],
 "Format.Spacing.Expanded": ["Character Spacing: %@ pt Wider", "文字間隔：%@ pt 広く", "문자 간격: %@pt 넓게", "字符间距：加宽 %@ 磅", "字元間距：加寬 %@ 點"],
 "Format.Spacing.Condensed": ["Character Spacing: %@ pt Narrower", "文字間隔：%@ pt 狭く", "문자 간격: %@pt 좁게", "字符间距：紧缩 %@ 磅", "字元間距：緊縮 %@ 點"],
 "Format.Position.Normal": ["Position: Normal", "位置：標準", "위치: 보통", "位置：标准", "位置：標準"],
 "Format.Position.Raised": ["Position: Raised %@ pt", "位置：%@ pt 上げる", "위치: %@pt 올림", "位置：提升 %@ 磅", "位置：提高 %@ 點"],
 "Format.Position.Lowered": ["Position: Lowered %@ pt", "位置：%@ pt 下げる", "위치: %@pt 내림", "位置：降低 %@ 磅", "位置：降低 %@ 點"],
 "Paragraph.Section.Pagination": ["Line and Page Breaks", "改ページと改行", "줄 및 페이지 나누기", "换行和分页", "分行與分頁"],
 "Paragraph.KeepWithNext": ["Keep with Next", "次の段落と分離しない", "다음 단락과 함께", "与下段同页", "與下段同頁"],
 "Paragraph.KeepLinesTogether": ["Keep Lines Together", "段落を分割しない", "현재 단락을 나누지 않음", "段中不分页", "段中不分頁"],
 "Paragraph.WidowControl": ["Widow Control", "改ページ時1行残して段落を区切らない", "페이지 나누기 시 한 줄 남기지 않음", "孤行控制", "遺留字串控制"],
 "Paragraph.PageBreakBefore": ["Page Break Before", "段落前で改ページする", "단락 앞에서 페이지 나누기", "段前分页", "段落前分頁"],
 "Paragraph.Section.Borders": ["Borders & Shading", "罫線と網かけ", "테두리 및 음영", "边框和底纹", "框線及網底"],
 "Paragraph.Borders": ["Borders", "罫線", "테두리", "边框", "框線"],
 "Paragraph.Borders.none": ["None", "なし", "없음", "无", "無"],
 "Paragraph.Borders.box": ["Box", "囲む", "상자", "方框", "方框"],
 "Paragraph.Borders.top": ["Top", "上", "위쪽", "上框线", "上框線"],
 "Paragraph.Borders.bottom": ["Bottom", "下", "아래쪽", "下框线", "下框線"],
 "Paragraph.Borders.topAndBottom": ["Top & Bottom", "上下", "위쪽 및 아래쪽", "上下框线", "上下框線"],
 "Paragraph.Borders.sides": ["Left & Right", "左右", "왼쪽 및 오른쪽", "左右框线", "左右框線"],
 "Paragraph.Borders.Custom": ["Custom", "カスタム", "사용자 지정", "自定", "自訂"],
 "Paragraph.BorderStyle": ["Line", "線種", "선", "线型", "線條"],
 "Border.single": ["Single", "実線", "실선", "单实线", "單線"],
 "Border.double": ["Double", "二重線", "이중선", "双线", "雙線"],
 "Border.dotted": ["Dotted", "点線", "점선", "点线", "點線"],
 "Border.dashed": ["Dashed", "破線", "파선", "虚线", "虛線"],
 "Border.thick": ["Thick", "太線", "굵은 선", "粗线", "粗線"],
 "Paragraph.Shading": ["Shading", "網かけ", "음영", "底纹", "網底"],
 "Paragraph.Section.Tabs": ["Tab Stops", "タブ位置", "탭 정지", "制表位", "定位點"],
 "Paragraph.Tabs.Footer": ["From the left margin.", "左余白からの位置です。", "왼쪽 여백에서부터의 위치입니다.", "从左边距算起。", "從左邊界算起。"],
 "Paragraph.AddTab": ["Add Tab Stop", "タブ位置を追加", "탭 정지 추가", "添加制表位", "加入定位點"],
 "Paragraph.RemoveTab": ["Remove Tab Stop", "タブ位置を削除", "탭 정지 제거", "删除制表位", "移除定位點"],
 "Paragraph.Tab.Alignment": ["Alignment", "配置", "정렬", "对齐方式", "對齊方式"],
 "Paragraph.Tab.Leader": ["Leader", "リーダー", "채움선", "前导符", "前置字元"],
 "Tab.left": ["Left", "左揃え", "왼쪽", "左对齐", "靠左"],
 "Tab.center": ["Center", "中央揃え", "가운데", "居中", "置中"],
 "Tab.right": ["Right", "右揃え", "오른쪽", "右对齐", "靠右"],
 "Tab.decimal": ["Decimal", "小数点揃え", "소수점", "小数点对齐", "小數點"],
 "Leader.none": ["No Leader", "リーダーなし", "채움선 없음", "无前导符", "無前置字元"],
 "Leader.dot": ["Dots", "点線", "점", "点", "點"],
 "Leader.hyphen": ["Dashes", "ハイフン", "대시", "短划线", "虛線"],
 "Leader.underscore": ["Line", "下線", "선", "下划线", "底線"],
 "Paragraph.Section.DropCap": ["Drop Cap", "ドロップキャップ", "단락 첫 문자 장식", "首字下沉", "首字放大"],
 "Paragraph.DropCap": ["Drop Cap", "ドロップキャップ", "단락 첫 문자 장식", "首字下沉", "首字放大"],
 "DropCap.none": ["None", "なし", "없음", "无", "無"],
 "DropCap.drop": ["Dropped", "本文内に表示", "본문", "下沉", "繞排"],
 "DropCap.margin": ["In Margin", "余白に表示", "여백", "悬挂", "邊界"],
 "Paragraph.DropCap.Lines": ["Lines to Drop: %d", "ドロップする行数：%d", "놓을 줄 수: %d", "下沉行数：%d", "放大行數：%d"],
 "List.Title": ["Bullets & Numbering", "箇条書きと段落番号", "글머리 기호 및 번호 매기기", "项目符号和编号", "項目符號及編號"],
 "List.Section.Bullets": ["Bullets", "箇条書き", "글머리 기호", "项目符号", "項目符號"],
 "List.Section.Numbering": ["Numbering", "段落番号", "번호 매기기", "编号", "編號"],
 "List.Section.Multilevel": ["Multilevel", "アウトライン", "다단계", "多级列表", "多層次清單"],
 "List.Section.Numbers": ["Numbering Value", "番号の値", "번호 값", "编号值", "編號值"],
 "List.StartAt": ["Start At: %d", "開始番号：%d", "시작 번호: %d", "起始编号：%d", "起始值：%d"],
 "List.Restart": ["Restart Numbering", "番号を振り直す", "번호 다시 매기기", "重新开始编号", "重新編號"],
 "List.Continue": ["Continue Numbering", "番号を継続する", "번호 계속 매기기", "继续编号", "繼續編號"],
 "Styles.All": ["All Styles", "すべてのスタイル", "모든 스타일", "所有样式", "所有樣式"],
 "Styles.Title": ["Styles", "スタイル", "스타일", "样式", "樣式"],
 "Styles.Section.All": ["Paragraph Styles", "段落スタイル", "단락 스타일", "段落样式", "段落樣式"],
 "Styles.New": ["New Style from Selection", "選択箇所から新しいスタイル", "선택 영역에서 새 스타일", "从所选内容新建样式", "從所選內容新增樣式"],
 "Styles.New.Placeholder": ["Style name", "スタイル名", "스타일 이름", "样式名称", "樣式名稱"],
 "Styles.New.Footer": ["Takes on the selected paragraph’s formatting.", "選択した段落の書式が使われます。", "선택한 단락의 서식을 사용합니다.", "采用所选段落的格式。", "採用所選段落的格式。"],
 "Styles.Modify": ["Modify Style", "スタイルを変更", "스타일 수정", "修改样式", "修改樣式"],
 "Styles.Size": ["Size: %@ pt", "サイズ：%@ pt", "크기: %@pt", "字号：%@ 磅", "大小：%@ 點"],
 "Styles.UpdateToMatch": ["Update to Match Selection", "選択箇所と一致するように更新", "선택 영역에 맞게 업데이트", "更新以匹配所选内容", "更新以符合所選內容"],
 "Styles.Modify.Footer": ["Changes every paragraph in this style.", "このスタイルのすべての段落が変わります。", "이 스타일의 모든 단락이 변경됩니다.", "会更改使用此样式的所有段落。", "會變更使用此樣式的所有段落。"],
 "Table.ExtendSelection": ["Extend Selection", "選択範囲を拡張", "선택 영역 확장", "扩展选择", "延伸選取範圍"],
 "Table.Select.Footer": ["Tap a cell to pick it. To pick several, turn on Extend Selection and tap the opposite corner.", "セルをタップして選択します。複数選択するには「選択範囲を拡張」をオンにして反対側の角をタップします。", "셀을 탭하여 선택합니다. 여러 셀을 선택하려면 선택 영역 확장을 켜고 반대쪽 모서리를 탭하십시오.", "轻点单元格以选择。要选择多个，请打开“扩展选择”并轻点对角。", "點一下儲存格即可選取。若要選取多個，請開啟「延伸選取範圍」並點一下對角。"],
 "Table.Cell": ["Cell", "セル", "셀", "单元格", "儲存格"],
 "Table.Cell.Text": ["Text", "テキスト", "텍스트", "文本", "文字"],
 "Table.Section.RowsColumns": ["Rows & Columns", "行と列", "행 및 열", "行和列", "列與欄"],
 "Table.InsertAbove": ["Insert Above", "上に行を挿入", "위에 삽입", "在上方插入", "插入上方列"],
 "Table.InsertBelow": ["Insert Below", "下に行を挿入", "아래에 삽입", "在下方插入", "插入下方列"],
 "Table.InsertLeft": ["Insert Left", "左に列を挿入", "왼쪽에 삽입", "在左侧插入", "插入左方欄"],
 "Table.InsertRight": ["Insert Right", "右に列を挿入", "오른쪽에 삽입", "在右侧插入", "插入右方欄"],
 "Table.DeleteRow": ["Delete Row", "行を削除", "행 삭제", "删除行", "刪除列"],
 "Table.DeleteColumn": ["Delete Column", "列を削除", "열 삭제", "删除列", "刪除欄"],
 "Table.Section.Cells": ["Cells", "セル", "셀", "单元格", "儲存格"],
 "Table.Merge": ["Merge Cells", "セルの結合", "셀 병합", "合并单元格", "合併儲存格"],
 "Table.Split": ["Split Cell", "セルの分割", "셀 분할", "拆分单元格", "分割儲存格"],
 "Table.ColumnWidth": ["Column Width: %@", "列の幅：%@", "열 너비: %@", "列宽：%@", "欄寬：%@"],
 "Table.Shading": ["Shading", "網かけ", "음영", "底纹", "網底"],
 "Table.Section.Table": ["Table", "表", "표", "表格", "表格"],
 "Table.Style": ["Style", "スタイル", "스타일", "样式", "樣式"],
 "Table.Style.None": ["None", "なし", "없음", "无", "無"],
 "Table.Look.HeaderRow": ["Header Row", "タイトル行", "머리글 행", "标题行", "標題列"],
 "Table.Look.BandedRows": ["Banded Rows", "縞模様（行）", "줄무늬 행", "镶边行", "帶狀列"],
 "Table.Look.FirstColumn": ["First Column", "最初の列", "첫째 열", "第一列", "第一欄"],
 "Table.Look.TotalRow": ["Total Row", "集計行", "요약 행", "汇总行", "合計列"],
 "Table.Borders": ["Borders", "罫線", "테두리", "边框", "框線"],
 "Table.Borders.all": ["All Borders", "格子", "모든 테두리", "所有框线", "所有框線"],
 "Table.Borders.outside": ["Outside Borders", "外枠", "바깥쪽 테두리", "外侧框线", "外框線"],
 "Table.Borders.inside": ["Inside Borders", "内側", "안쪽 테두리", "内部框线", "內框線"],
 "Table.Borders.none": ["No Borders", "枠なし", "테두리 없음", "无框线", "無框線"],
 "Table.RepeatHeader": ["Repeat as Header Row", "タイトル行の繰り返し", "머리글 행 반복", "重复标题行", "重複標題列"],
 "PageSetup.Section.Section": ["Section", "セクション", "구역", "节", "節"],
 "PageSetup.Section.Footer": ["Applies to the section the cursor is in. Columns are saved for Word; Libretto lays the text out in one.", "カーソルのあるセクションに適用されます。段組みはWord用に保存されます。Librettoでは1段で表示されます。", "커서가 있는 구역에 적용됩니다. 단은 Word용으로 저장되며 Libretto에서는 한 단으로 표시됩니다.", "应用于光标所在的节。分栏会为 Word 存储；Libretto 以单栏显示文本。", "套用到游標所在的節。欄會為 Word 儲存；Libretto 以單欄顯示文字。"],
 "PageSetup.Start": ["Section Starts", "セクションの開始位置", "구역 시작", "节的起始位置", "節的起始位置"],
 "PageSetup.Columns": ["Columns", "段数", "단", "栏数", "欄數"],
 "SectionStart.nextPage": ["New Page", "次のページから開始", "다음 페이지", "新建页", "新頁"],
 "SectionStart.continuous": ["Continuous", "現在の位置から開始", "이어서", "连续", "接續本頁"],
 "SectionStart.evenPage": ["Even Page", "偶数ページから開始", "짝수 페이지", "偶数页", "偶數頁"],
 "SectionStart.oddPage": ["Odd Page", "奇数ページから開始", "홀수 페이지", "奇数页", "奇數頁"],
 "Insert.Breaks": ["Breaks", "区切り", "나누기", "分隔符", "分隔設定"],
 "Insert.ColumnBreak": ["Column Break", "段区切り", "단 나누기", "分栏符", "分欄符號"],
 "Insert.SectionNextPage": ["Section Break (Next Page)", "セクション区切り（次のページから開始）", "구역 나누기(다음 페이지부터)", "分节符（下一页）", "分節符號（下一頁）"],
 "Insert.SectionContinuous": ["Section Break (Continuous)", "セクション区切り（現在の位置から開始）", "구역 나누기(이어서)", "分节符（连续）", "分節符號（接續本頁）"],
 "Insert.SectionEvenPage": ["Section Break (Even Page)", "セクション区切り（偶数ページから開始）", "구역 나누기(짝수 페이지부터)", "分节符（偶数页）", "分節符號（自下個偶數頁起）"],
 "Insert.SectionOddPage": ["Section Break (Odd Page)", "セクション区切り（奇数ページから開始）", "구역 나누기(홀수 페이지부터)", "分节符（奇数页）", "分節符號（自下個奇數頁起）"],
 "Panel.Navigator.Title": ["Navigation", "ナビゲーション", "탐색", "导航", "導覽"],
 "Toolbar.Navigator": ["Navigation", "ナビゲーション", "탐색", "导航", "導覽"],
 "Insert.Bookmark": ["Bookmark", "ブックマーク", "책갈피", "书签", "書籤"],
 "Navigator.Show": ["Show", "表示", "보기", "显示", "顯示"],
 "Navigator.Headings": ["Headings", "見出し", "제목", "标题", "標題"],
 "Navigator.Bookmarks": ["Bookmarks", "ブックマーク", "책갈피", "书签", "書籤"],
 "Navigator.NoHeadings": ["No Headings", "見出しなし", "제목 없음", "无标题", "沒有標題"],
 "Navigator.NoHeadings.Description": ["Paragraphs in heading styles show here.", "見出しスタイルの段落がここに表示されます。", "제목 스타일의 단락이 여기에 표시됩니다.", "使用标题样式的段落会显示在此处。", "使用標題樣式的段落會顯示在這裡。"],
 "Navigator.Bookmark.Placeholder": ["Bookmark name", "ブックマーク名", "책갈피 이름", "书签名", "書籤名稱"],
 "Navigator.Bookmark.Add": ["Add Bookmark", "ブックマークを追加", "책갈피 추가", "添加书签", "加入書籤"],
 "Navigator.Bookmark.Footer": ["Marks the selected text, or the cursor’s place. Link to it with # and its name.", "選択したテキストまたはカーソル位置に付けます。「#」と名前でリンクできます。", "선택한 텍스트나 커서 위치를 표시합니다. # 뒤에 이름을 붙여 링크할 수 있습니다.", "标记所选文本或光标位置。可用 # 加名称链接到它。", "標記所選文字或游標位置。可用 # 加名稱連結到它。"],
 "Navigator.NoBookmarks": ["No bookmarks", "ブックマークなし", "책갈피 없음", "无书签", "沒有書籤"],
 "Navigator.ShowHidden": ["Show Hidden Bookmarks", "隠しブックマークを表示", "숨겨진 책갈피 보기", "显示隐藏书签", "顯示隱藏書籤"],
 "Panel.CrossReference.Title": ["Cross-reference", "相互参照", "상호 참조", "交叉引用", "交互參照"],
 "CrossReference.Insert": ["Refer To", "参照先", "참조", "引用内容", "參照"],
 "CrossReference.Text": ["Its Text", "テキスト", "텍스트", "文本", "文字"],
 "CrossReference.Page": ["Its Page Number", "ページ番号", "페이지 번호", "页码", "頁碼"],
 "Toolbar.UpdateFields": ["Update Fields", "フィールドの更新", "필드 업데이트", "更新域", "更新功能變數"],
 "Insert.Field": ["Field", "フィールド", "필드", "域", "功能變數"],
 "Field.Date": ["Date", "日付", "날짜", "日期", "日期"],
 "Field.Time": ["Time", "時刻", "시간", "时间", "時間"],
 "Field.Page": ["Page Number", "ページ番号", "페이지 번호", "页码", "頁碼"],
 "Field.PageCount": ["Number of Pages", "総ページ数", "총 페이지 수", "总页数", "總頁數"],
 "Field.CaptionFigure": ["Figure Caption", "図表番号（図）", "그림 캡션", "图题注", "圖表標號（圖）"],
 "Field.CaptionTable": ["Table Caption", "図表番号（表）", "표 캡션", "表题注", "圖表標號（表）"],
 "Field.CaptionEquation": ["Equation Caption", "図表番号（数式）", "수식 캡션", "公式题注", "圖表標號（方程式）"],
 "Field.CrossReference": ["Cross-reference…", "相互参照…", "상호 참조…", "交叉引用…", "交互參照…"],
 "Caption.Figure": ["Figure", "図", "그림", "图", "圖"],
 "Caption.Table": ["Table", "表", "표", "表", "表"],
 "Caption.Equation": ["Equation", "数式", "수식", "公式", "方程式"],
 "Insert.Contents": ["Table of Contents", "目次", "목차", "目录", "目錄"],
 "Contents.Empty": ["No headings for a table of contents", "目次にする見出しがありません", "목차를 만들 제목이 없습니다", "没有可用于目录的标题", "沒有可用於目錄的標題"],
 "Panel.Symbols.Title": ["Symbols", "記号と特殊文字", "기호", "符号", "符號"],
 "Insert.Symbol": ["Symbol", "記号と特殊文字", "기호", "符号", "符號"],
 "Symbol.Recent": ["Recently Used", "最近使用した記号", "최근 사용한 기호", "最近使用", "最近使用"],
 "Symbol.Special": ["Special Characters", "特殊文字", "특수 문자", "特殊字符", "特殊字元"],
 "Symbol.EmDash": ["Em Dash", "全角ダッシュ", "전각 대시", "长破折号", "長破折號"],
 "Symbol.EnDash": ["En Dash", "半角ダッシュ", "반각 대시", "短破折号", "短破折號"],
 "Symbol.NonBreakingSpace": ["Non-Breaking Space", "改行なしスペース", "줄 바꿈하지 않는 공백", "不间断空格", "不分行空格"],
 "Symbol.NonBreakingHyphen": ["Non-Breaking Hyphen", "改行なしハイフン", "줄 바꿈하지 않는 하이픈", "不间断连字符", "不分行連字號"],
 "Symbol.OptionalHyphen": ["Optional Hyphen", "任意指定のハイフン", "선택적 하이픈", "可选连字符", "選擇性連字號"],
 "Symbol.Ellipsis": ["Ellipsis", "三点リーダー", "줄임표", "省略号", "刪節號"],
 "Symbol.Copyright": ["Copyright", "著作権記号", "저작권", "版权", "版權"],
 "Symbol.Registered": ["Registered", "登録商標", "등록 상표", "注册商标", "註冊商標"],
 "Symbol.Trademark": ["Trademark", "商標", "상표", "商标", "商標"],
 "Symbol.Section": ["Section", "セクション記号", "섹션", "章节号", "章節符號"],
 "Symbol.Paragraph": ["Paragraph", "段落記号", "단락 기호", "段落标记", "段落符號"],
 "Symbol.Degree": ["Degree", "度", "도", "度", "度"],
 "Symbol.Group.Punctuation": ["Punctuation", "句読点", "문장 부호", "标点", "標點"],
 "Symbol.Group.Math": ["Math", "数学記号", "수학", "数学", "數學"],
 "Symbol.Group.Arrows": ["Arrows", "矢印", "화살표", "箭头", "箭頭"],
 "Symbol.Group.Greek": ["Greek", "ギリシャ文字", "그리스 문자", "希腊字母", "希臘字母"],
 "Symbol.Group.Currency": ["Currency", "通貨記号", "통화", "货币", "貨幣"],
 "Symbol.Group.Other": ["Other", "その他", "기타", "其他", "其他"],
 "Panel.Picture.Title": ["Picture", "画像", "사진", "图片", "圖片"],
 "ActionBar.EditPicture": ["Edit Picture", "画像を編集", "사진 편집", "编辑图片", "編輯圖片"],
 "Picture.Section.Size": ["Size", "サイズ", "크기", "大小", "大小"],
 "Picture.Width": ["Width: %@ pt", "幅：%@ pt", "너비: %@pt", "宽度：%@ 磅", "寬度：%@ 點"],
 "Picture.Height": ["Height: %@ pt", "高さ：%@ pt", "높이: %@pt", "高度：%@ 磅", "高度：%@ 點"],
 "Picture.OriginalSize": ["Original Size", "元のサイズ", "원본 크기", "原始大小", "原始大小"],
 "Picture.Section.Crop": ["Crop", "トリミング", "자르기", "裁剪", "裁切"],
 "Picture.Crop.Left": ["Left", "左", "왼쪽", "左", "左"],
 "Picture.Crop.Right": ["Right", "右", "오른쪽", "右", "右"],
 "Picture.Crop.Top": ["Top", "上", "위쪽", "上", "上"],
 "Picture.Crop.Bottom": ["Bottom", "下", "아래쪽", "下", "下"],
 "Picture.Section.Wrap": ["Text Wrapping", "文字列の折り返し", "텍스트 줄 바꿈", "文字环绕", "文繞圖"],
 "Picture.Wrap": ["Wrap", "折り返し", "줄 바꿈", "环绕", "繞圖"],
 "Wrap.inline": ["In Line with Text", "行内", "텍스트 줄 안", "嵌入型", "與文字排列"],
 "Wrap.square": ["Square", "四角形", "정사각형", "四周型", "矩形"],
 "Wrap.tight": ["Tight", "外周", "빽빽하게", "紧密型", "緊密"],
 "Wrap.topAndBottom": ["Top and Bottom", "上下", "위쪽 및 아래쪽", "上下型", "上及下"],
 "Wrap.behindText": ["Behind Text", "背面", "텍스트 뒤", "衬于文字下方", "文字在前"],
 "Wrap.inFrontOfText": ["In Front of Text", "前面", "텍스트 앞", "浮于文字上方", "文字在後"],
 "Picture.Horizontal": ["Horizontal Position", "横方向の位置", "가로 위치", "水平位置", "水平位置"],
 "Picture.Vertical": ["Below Paragraph: %@ pt", "段落からの位置：%@ pt", "단락 아래: %@pt", "距段落：%@ 磅", "距段落：%@ 點"],
 "Picture.Delete": ["Delete Picture", "画像を削除", "사진 삭제", "删除图片", "刪除圖片"],
 "Picture.None": ["No Picture Selected", "画像が選択されていません", "선택된 사진 없음", "未选择图片", "未選取圖片"],
 "Insert.Shape": ["Shape", "図形", "도형", "形状", "圖案"],
 "Insert.TextBox": ["Text Box", "テキストボックス", "텍스트 상자", "文本框", "文字方塊"],
 "Shape.rect": ["Rectangle", "四角形", "직사각형", "矩形", "矩形"],
 "Shape.roundRect": ["Rounded Rectangle", "角丸四角形", "둥근 직사각형", "圆角矩形", "圓角矩形"],
 "Shape.ellipse": ["Oval", "楕円", "타원", "椭圆", "橢圓"],
 "Shape.triangle": ["Triangle", "三角形", "삼각형", "三角形", "三角形"],
 "Shape.diamond": ["Diamond", "ひし形", "다이아몬드", "菱形", "菱形"],
 "Shape.rightArrow": ["Arrow", "矢印", "화살표", "箭头", "箭號"],
 "Shape.star5": ["Star", "星", "별", "星形", "星形"],
 "Shape.line": ["Line", "直線", "선", "直线", "直線"],
 "Picture.Section.Shape": ["Shape", "図形", "도형", "形状", "圖案"],
 "Shape.Text": ["Text", "テキスト", "텍스트", "文本", "文字"],
 "Shape.Fill": ["Fill", "塗りつぶし", "채우기", "填充", "填滿"],
 "Shape.Line": ["Line", "線", "선", "线条", "線條"],
 "Panel.Equation.Title": ["Equation", "数式", "수식", "公式", "方程式"],
 "Insert.Equation": ["Equation", "数式", "수식", "公式", "方程式"],
 "ActionBar.EditEquation": ["Edit Equation", "数式を編集", "수식 편집", "编辑公式", "編輯方程式"],
 "Equation.Placeholder": ["x = (-b ± sqrt(b^2 - 4ac))/(2a)", "x = (-b ± sqrt(b^2 - 4ac))/(2a)", "x = (-b ± sqrt(b^2 - 4ac))/(2a)", "x = (-b ± sqrt(b^2 - 4ac))/(2a)", "x = (-b ± sqrt(b^2 - 4ac))/(2a)"],
 "Equation.Footer": ["a/b is a fraction, x^2 and x_i are scripts, sqrt(x) a root, sum_(i=1)^n, prod and int big operators, and \\alpha, \\pm, \\infty and the like symbols. Brackets group.", "a/b は分数、x^2 と x_i は上付き・下付き、sqrt(x) は根号、sum_(i=1)^n・prod・int は大型演算子、\\alpha・\\pm・\\infty などは記号です。かっこでまとめます。", "a/b는 분수, x^2와 x_i는 위 첨자와 아래 첨자, sqrt(x)는 근호, sum_(i=1)^n·prod·int는 큰 연산자, \\alpha·\\pm·\\infty 등은 기호입니다. 괄호로 묶습니다.", "a/b 为分数，x^2 和 x_i 为上下标，sqrt(x) 为根式，sum_(i=1)^n、prod、int 为大型运算符，\\alpha、\\pm、\\infty 等为符号。用括号分组。", "a/b 為分數，x^2 和 x_i 為上下標，sqrt(x) 為根號，sum_(i=1)^n、prod、int 為大型運算子，\\alpha、\\pm、\\infty 等為符號。用括號分組。"],
 "Equation.Insert": ["Insert Equation", "数式を挿入", "수식 삽입", "插入公式", "插入方程式"],
 "Equation.Update": ["Update Equation", "数式を更新", "수식 업데이트", "更新公式", "更新方程式"],
 "Equation.Delete": ["Delete Equation", "数式を削除", "수식 삭제", "删除公式", "刪除方程式"],
}

reuse = ["Alert.Error.Title", "Common.OK", "Format.ClearAll", "Format.Section.Text", "Format.Text.Size",
         "Format.Text.Size.Decrease", "Format.Text.Size.Increase", "Toolbar.Bold", "Toolbar.Italic",
         "Toolbar.Redo", "Toolbar.Strikethrough", "Toolbar.Underline", "Toolbar.Undo",
         "Toolbar.UnsupportedFeatures.Label", "ColorSwatches.More.Text.Accessibility", "ColorSwatches.MoreColours",
         "ColorSwatches.None.Text.Accessibility", "ColorSwatches.Swatch.Text.Accessibility",
         "ColorSwatches.More.Fill.Accessibility", "ColorSwatches.None.Fill.Accessibility",
         "ColorSwatches.Swatch.Fill.Accessibility", "ColorSwatches.More.Border.Accessibility",
         "ColorSwatches.None.Border.Accessibility", "ColorSwatches.Swatch.Border.Accessibility"]
reuse += [k for k in ["Color.Black", "Color.Blue", "Color.Brown", "Color.Cyan", "Color.Green", "Color.Grey",
          "Color.Grey2", "Color.Grey3", "Color.Grey4", "Color.Grey5", "Color.Grey6", "Color.Indigo", "Color.Mint",
          "Color.Orange", "Color.Pink", "Color.Purple", "Color.Red", "Color.Teal", "Color.White", "Color.Yellow"]]

tables = json.load(open(tables_path))["strings"]
strings = {}
for key, values in S.items():
    strings[key] = {"extractionState": "manual", "localizations": {
        lang: {"stringUnit": {"state": "translated", "value": value}} for lang, value in zip(LANGS, values)}}
for key in reuse:
    if key not in tables:
        sys.exit(f"Tables has no {key}")
    entry = dict(tables[key])
    entry["extractionState"] = "manual"
    strings[key] = entry
    missing = [lang for lang in LANGS if lang not in entry.get("localizations", {})]
    if missing:
        sys.exit(f"{key} lacks {missing}")

catalog = {"sourceLanguage": "en", "strings": dict(sorted(strings.items())), "version": "1.0"}
with open(out_path, "w") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
print(len(strings), "strings")
